### ISSUE TITLE
Origin IP found, Cloudflare bypassed | Non-Cloudflare IP

### ISSUE THREAD

**Issue by Vinaysati** [bitcoin-core/bitcoincore.org#1002]
Summary:

The software does not restrict or incorrectly restrict access to a resource from an unauthorized actor.

Access control involves the use of several protection mechanisms such as:

Authentication (proving the identity of an actor)

Authorization (ensuring that a given actor can access a resource), and

Accountability (tracking of activities that were performed)

When any mechanism is not applied or otherwise fails, attackers can compromise the security of the software by gaining privileges, reading sensitive information, executing commands, evading detection, etc.

Bug-Description:

Cloudflare/Akamai/Google-cloud/Netlify/Azure is a useful tool to enhance site performance, accelerate the access speed and improve the visitors’ experience. It is a CDN, DNS, Security(Web Firewall), Optimer, Analytics, etc. all in one package. In a simple way, you can say that Cloudflare makes the application loading time faster and saves it from attacks such as SQLi and XSS to save your users from being hacked. If you are unsure about how to check if a web application is using Cloudflare, you can simply use an extension such as Wappaylzer which shows the different technologies, Frameworks, and CDN’s the application is using. You can download it from here if you don’t have this or any other extension like it. Its usage is pretty simple.

It is possible to access origin IP servers served by Nginx and not Cloudflare. Even though these IPs don't serve a functional version of the app it is possible to enable DDoS attacks by bypassing Cloudflare protections.

Bug-Status:

Weakness: Improper Access Control

Reported to: bitco.in

Severity: Medium / 5.6

CVSS: CWE-284 (CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L)

Scope: Confidentiality, Availability, Access Control, Integrity

Affected-URL : bitco.in

Steps To Reproduce:

Go to [censys.io](http://censys.io/)

Search Keyword "ssl:[target.com](http://target.com/) 200" --> [https://www.censys.io/search?query=ssl%3Atarget.com+200&page=1](https://www.shodan.io/search?query=ssl%3Atarget.com+200&page=1)

Scroll Down below you found the Original IP Revealed.

i.e:  https://173.199.148.210/

Impact:

Cloudflare bypasses can have a significant impact, as any adversary is now able to communicate with the origin server directly, enabling them to perform unfiltered attacks (such as denial-of-service), and data retrieval.

It could enable MITM attacks.

Reference:

https://blog.detectify.com/2019/07/31/bypassing-cloudflare-waf-with-the-origin-server-ip-address/

https://enciphers.com/bypassing-cloudflare-waf-to-get-more-vulnerabilities/

https://geekflare.com/find-real-ip-origin-address-of-website/

https://cwe.mitre.org/data/definitions/284.html

Regards

Vinay Sati
![Screenshot 2024-02-04 213904](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/8a6c0f77-9b00-4248-93ae-c5d129f6c746)

**Comment by achow101** [comment]
bitcoincore.org is a static website. There is no need to use a WAF, and Cloudflare is intentionally not used.
