### ISSUE TITLE
Improper Access Control

### ISSUE THREAD

**Issue by Vinaysati** [bitcoin-core/bitcoincore.org#1003]
The software does not restrict or incorrectly restrict access to a resource from an unauthorized actor.

Access control involves the use of several protection mechanisms such as:

Authentication (proving the identity of an actor)

Authorization (ensuring that a given actor can access a resource), and

Accountability (tracking of activities that were performed)

When any mechanism is not applied or otherwise fails, attackers can compromise the security of the software by gaining privileges, reading sensitive information, executing commands, evading detection, etc.

Bug-Description:

Cloudflare/Akamai/Google-cloud/Netlify/Azure is a useful tool to enhance site performance, accelerate the access speed and improve the visitors’ experience. It is a CDN, DNS, Security(Web Firewall), Optimer, Analytics, etc. all in one package. In a simple way, you can say that Cloudflare makes the application loading time faster and saves it from attacks such as SQLi and XSS to save your users from being hacked. If you are unsure about how to check if a web application is using Cloudflare, you can simply use an extension such as Wappaylzer which shows the different technologies, Frameworks, and CDN’s the application is using. You can download it from here if you don’t have this or any other extension like it. Its usage is pretty simple.

It is possible to access origin IP servers served by Nginx and not Cloudflare. Even though these IPs don't serve a functional version of the app it is possible to enable DDoS attacks by bypassing Cloudflare protections.

Bug-Status:

Weakness: Improper Access Control

Reported to: [bitcoincore.org](http://bitcoincore.org/)

Severity: Medium / 5.6

CVSS: CWE-284 (CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L)

Scope: Confidentiality, Availability, Access Control, Integrity

Affected-URL : [bitcoincore.org](http://bitcoincore.org/)

Steps To Reproduce:

Go to [censys.io](http://censys.io/)

Search Keyword "ssl:[target.com](http://target.com/) 200" --> [https://www.censys.io/search?query=ssl%3Atarget.com+200&page=1](https://www.shodan.io/search?query=ssl%3Atarget.com+200&page=1)

Scroll Down below you found the Original IP Revealed.

i.e:  https://65.21.29.208/explorer/
       https://198.251.83.116/

and many more

Impact:

Cloudflare bypasses can have a significant impact, as any adversary is now able to communicate with the origin server directly, enabling them to perform unfiltered attacks (such as denial-of-service), and data retrieval.

It could enable MITM attacks.

Reference:

https://blog.detectify.com/2019/07/31/bypassing-cloudflare-waf-with-the-origin-server-ip-address/

https://enciphers.com/bypassing-cloudflare-waf-to-get-more-vulnerabilities/

https://geekflare.com/find-real-ip-origin-address-of-website/

https://cwe.mitre.org/data/definitions/284.html

Regards

Vinay sati
![Screenshot 2024-02-04 212433](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/50bb5660-0b72-4e39-886a-03bafb2673c3)
![Screenshot 2024-02-04 212444](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/6698a829-d33a-4e3b-af27-709e7d090caf)

**Comment by achow101** [comment]
bitcoincore.org is a static website. There is no need for a WAF and Cloudflare is intentionally not used.

**Comment by Vinaysati** [comment]
but @achow101  you can see your static website are use cloudflare and you see i am bypass your ip 
![Screenshot 2024-02-05 220617](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/4a6fd82b-1121-4d85-a2ef-d8277a9e4562)

**Comment by achow101** [comment]
The website you show in your screenshot is not bitcoincore.org

**Comment by Vinaysati** [comment]
check this
![Screenshot 2024-02-05 223812](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/001c0741-0e51-4f2f-a4f2-48f13d2a9fa9)

**Comment by achow101** [comment]
In what way does that make it bitcoincore.org? It is a website that links to assets hosted on bitcoincore.org, but that doesn't mean it is owned or operated by bitcoincore.org. The IP addresses for bitcoincore.org can be looked up with a simple DNS lookup, and none of them are Cloudflare IPs. The website you are reporting an issue for is unrelated to this repo.

**Comment by Vinaysati** [comment]
Sir, this IP is directly accessing your website whereas this website is using cloud flare and I am able to get the IP of your website by bypassing the flare flare.  You understand that cloudflare is used to block real ip and suspesis ip  website.

**Comment by Vinaysati** [comment]
Sir, this IP is directly accessing your website whereas this website is using cloud flare and I am able to get the IP of your website by bypassing the flare flare.  You understand that cloudflare is used to block real ip and suspesis ip  website.

**Comment by Vinaysati** [comment]
check this one this is bitcoin forum
![Uploading Screenshot 2024-02-05 230911.png…]()

**Comment by Vinaysati** [comment]
check this one this is bitcoin forum
![Uploading Screenshot 2024-02-05 230911.png…]()

**Comment by Vinaysati** [comment]
check this
![Screenshot 2024-02-05 231205](https://github.com/bitcoin-core/bitcoincore.org/assets/73187537/2a2de34b-c0df-4967-8bc2-4472c2de04f6)

**Comment by Vinaysati** [comment]
@achow101 sir check this
