### ISSUE TITLE
Re-upload Bitcoin whitepaper after UK judge ruling

### ISSUE THREAD

**Issue by Lucienest** [bitcoin-core/bitcoincore.org#1008]
The Bitcoin site previously took down the whitepaper in fear of legal litigation by Craig Wright (self-proclaimed Satoshi Nakamoto)
but since the UK judge ruled out his false claim and the copyright of bitcoin whitepaper
[Craig Wright Is Not Satoshi, Didn't Author Bitcoin Whitepaper, Judge Rules
](https://www.coindesk.com/policy/2024/03/14/craig-wright-not-satoshi-didnt-author-bitcoin-whitepaper-judge-rules/)

you can freely re-upload the Bitcoin whitepaper

**Comment by fanquake** [comment]
Done in #1024.
