### ISSUE TITLE
Add download links for Binaries and source versions.

### ISSUE THREAD

**Issue by creationlayer** [bitcoin-core/bitcoincore.org#104]
I would like to include some guides on how to run a node, and get the code up and running. Currently download links for Binaries and various source version would need to go to Bitcoin.org.

Do you think we could add them on this site for availability to expand some of the resources, and make it clear bitcoincore software is available from bitcoincore?

**Comment by btcdrak** [comment]
We have no plans to change the download location of the binaries at this time. However, we welcome documentation/guides.

**Comment by laanwj** [comment]
There are excellent guides on setting up and running a node on bitcoin.org. See: https://bitcoin.org/en/full-node

Documentation is great, but let's not duplicate their efforts. It is less confusing for users to have one conclusive document than two half-finished ones. So better to contribute to that one.

**Comment by creationlayer** [comment]
I understand, thank you very much.

I'll move on to something else that is not a duplication.
