### ISSUE TITLE
doxygen.bitcoincore.org unreachable

### ISSUE THREAD

**Issue by stickies-v** [bitcoin-core/bitcoincore.org#1068]
It appears https://doxygen.bitcoincore.org/ is down at least since 2024-09-13 ([irc](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2024-09-13#1052094)):

```
% curl doxygen.bitcoincore.org
curl: (28) Failed to connect to doxygen.bitcoincore.org port 80 after 75051 ms: Couldn't connect to server
```

```
% dig doxygen.bitcoincore.org +short A
163.172.210.223
```

Note: this subdomain is referenced in the Bitcoin Core documentation, notably in [`README.md`](https://github.com/bitcoin/bitcoin/blob/6a370435526875a441001be8c44c9b94a2361c8c/doc/README.md?plain=1#L56) and [`developer-notes.md`](https://github.com/bitcoin/bitcoin/blob/6a370435526875a441001be8c44c9b94a2361c8c/doc/developer-notes.md?plain=1#L629)

**Comment by laanwj** [comment]
https://doxygen.bitcoincore.org/ is up and running again
(server was moved to a new IP, and had to update the crontab script for cmake)

**Comment by laanwj** [comment]
It's up but it's not updating. Will look into it.

**Comment by laanwj** [comment]
Are you sure? it should have. To be sure, i've re-run it. Is there anything in particular missing?
