### ISSUE TITLE
Links from the generated RPC docs back to version-tag are broken

### ISSUE THREAD

**Issue by hodlinator** [bitcoin-core/bitcoincore.org#1071]
Example:
https://bitcoincore.org/en/doc/28.0.0/ currently has a link in the left column:
> Documentation exported from [Bitcoin Core 28.0.0](https://github.com/bitcoin/bitcoin/tree/v28.0.0)

The URL is https://github.com/bitcoin/bitcoin/tree/v28.0.0 but the URL for the correct tag is https://github.com/bitcoin/bitcoin/tree/v28.0, so GitHub gives users 404s.

URLs for versions using the old 0.x.y scheme work.

**Comment by stickies-v** [comment]
Suggested fix in https://github.com/bitcoin-core/bitcoincore.org/pull/1073
