### ISSUE TITLE
Team of people contributing to Bitcoin Core on the website

### ISSUE THREAD

**Issue by Feri22** [bitcoin-core/bitcoincore.org#137]
I noticed many people directly thinks Core = Blockstream...If we could show them https://www.blockstream.com/team/ and for example https://bitcoin.org/en/dev-team for compare, it would be easy way to argument and "verify" who from Core works for Blockstream...Bitcoin classic has it on their homepage...

So please add list of developers, who are actively contributing to Core so we can show it to world, that many devs support Core...not only for the Blockstream FUD issue, but generaly..every project has a list of team members

**Comment by btcdrak** [comment]
I agree this could be a good thing to show the most active developers.

**Comment by laanwj** [comment]
Also always helps to link to the credits for some release:
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.12.0.md#credits

**Comment by Feri22** [comment]
Link to the credits surely helps, but i think average bitcoin user won't find it easily...in these times, when there is lot of FUD abot Core devs, i believe it should be on the website of Core, if not directly on the homepage. Many people are accusing Core devs = Blockstream. Let's show them it is just a fud...

**Comment by btcdrak** [comment]
@Feri22 I am working on a proposal. Will update when I have something for review. Feel free to contact me on email/IRC/Slack.

**Comment by Feri22** [comment]
Great

**Comment by btcdrak** [comment]
Done.
