### ISSUE TITLE
GPG keys no longer reachable

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/bitcoincore.org#170]
Page:
https://bitcoincore.org/en/list/announcements/join/

Reported by cjcj / IRC:
```
[16:24:21]  <cjcj>	Just an FYI: none of the GPG keys listed https://bitcoincore.org/en/list/announcements/join/ are reachable
```

**Comment by MarcoFalke** [comment]
I broke this :)))

This is easy to fix by replacing `gitian-downloader` with `gitian-keys`

c.f. https://github.com/bitcoin/bitcoin/pull/7870
