### ISSUE TITLE
Re-Providing Email To List Gives Wrong Message

### ISSUE THREAD

**Issue by Daunus** [bitcoin-core/bitcoincore.org#251]
For the mailing list if you provide an email that was already on the mailing list you get the message:

'We have sent you an email to confirm your subscription to the Bitcoin Core announcements list.'

No email gets sent. It would be better if it said something like:

'You have already subscribed to the Bitcoin Core announcements list.'

----

Minor issue :). I must of signed up months ago and was confused why it did not let me sign up when I tried now.

 I am not sure if it can be easily fixed, since you guys use https://sendy.co/ for emails right? Maybe thats just how sendy works.

EDIT: Sendy does seem to have a have subscription-status api call https://sendy.co/api

---
EDIT:

If you provided your email but have not yet confirmed, and provide your email again, you will be shown the same message again and receive a new confirmation email. 

So that is working correctly. 

Also, to clarify, the mailing list does not subscribe you to receive the articles added to the blog or faq section, right?

**Comment by btcdrak** [comment]
> Also, to clarify, the mailing list does not subscribe you to receive the articles added to the blog or faq section, right?

The list's purpose is really for important announcements, like new releases and security warnings. Please use the RSS feeds provided for blog updates.

I'll look into the other issue, thanks for reporting.

**Comment by MarcoFalke** [comment]
Can be closed. There is no sendy support anymore

**Comment by laanwj** [comment]
Correct.
The [bitcoin-core-dev](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-core-dev) mailing list is the notification list now.
