### ISSUE TITLE
Antivirus strange alert

### ISSUE THREAD

**Issue by alpet83** [bitcoin-core/bitcoincore.org#284]
My antivirus Kaspersky Total Security popup alert about bitcoin-qt.exe is UDS:DangerousObject.Multi.Generic, by Kaspersky Application Advisor rating: http://whitelisting.kaspersky.com/advisor-ru#search/d02b43b6ac5e2f320cb9a195ec6d54bd

Suspicious bitcoin-qt contains in bitcoin-0.13.1-win64.zip and slightly different by size and contents relative bitcoin-qt.exe from bitcoin-0.13.1-win64-setup.exe (without warning from antivirus):
http://whitelisting.kaspersky.com/advisor-ru#search/f9255de5ad8f4fd675718d0d6bb96fd1

Why this files are different?

**Comment by btcdrak** [comment]
File corruption, could be many reasons. Please validate binaries according to the signed hashes or gitian signatures.
