### ISSUE TITLE
verify bitcoin core

### ISSUE THREAD

**Issue by almoharebh** [bitcoin-core/bitcoincore.org#295]
C:\Users\User>gpg --verify SHA256SUMS.asc
gpg: conversion from `utf-8' to `CP720' not available
gpg: can't open `SHA256SUMS.asc': No such file or directory
gpg: verify signatures failed: No such file or directory.
-----------------------------------------------------
C:\Users\User>gpg --sign-key laanwj@gmail.com
gpg: conversion from `utf-8' to `CP720' not available

pub  4096R/36C2E964  created: 2015-06-24  expires: 2017-02-13  usage: SC
                     trust: full          validity: full
[  full  ] (1). Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>

"Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>" was already signed by key 82DF5D26
Nothing to sign with key 82DF5D26.

is this verify right

**Comment by TheBlueMatt** [comment]
gpg: can't open `SHA256SUMS.asc': No such file or directory

Is your actual error. the SHA256SUMS file is missing.

**Comment by almoharebh** [comment]
yes. but I download it on my computer

**Comment by almoharebh** [comment]
is this right way to verify bitcoin core

**Comment by MarcoFalke** [comment]
Please follow the instructions on http://bitcoin.stackexchange.com/a/50186
