### ISSUE TITLE
Nunca me llego el pago...

### ISSUE THREAD

**Issue by grexl** [bitcoin-core/bitcoincore.org#300]
Tengo un error o fallo de mi cartera a la cual le envíe dinero a través de BlockChain y nunca llego a mi cartera, Su soporte me explico que el pago podría durar entre 1 a 3 hora pero ya a pasado 3 dias y el programa no muestra nada de dinero en la cuenta, también muestra una barra cargando diciendo ¨Sincronizando con la red¨ pero nunca carga.

**Comment by CodeShark** [comment]
Lo sentimos, pero este no es el lugar para este tipo de soporte técnico. Trate en StackExchange. Quiza haya alguien que pueda asistir allí.
