### ISSUE TITLE
commits/PRs ommited from release nodes

### ISSUE THREAD

**Issue by rebroad** [bitcoin-core/bitcoincore.org#306]
I have noticed in the release notes for 0.13.1 and 0.13.2 that my contributions to the project were not mentioned, nor was I mentioned in the credits section. Is this intentional?

**Comment by laanwj** [comment]
Minor (e.g. move-only, typo) PRs are omitted from the release notes on purpose, to keep the length of the list down. This is mentioned.

However the credits section is directly generated from git so no one (that authored at least one commit) should be missing there. Can you be precise as to what PRs/commits this is about?
