### ISSUE TITLE
Listing bitcoin clients

### ISSUE THREAD

**Issue by ruimarinho** [bitcoin-core/bitcoincore.org#328]
Is there an interest in adding a list of clients for bitcoin (e.g. go-bitcoin, bitcoin (JS), bitcoin-python, etc) on the main website?

Secondly, would you like to host the popular JS client https://npmjs.com/bitcoin under the `bitcoin-core` organization?

**Comment by btcdrak** [comment]
This website is more focused to the Bitcoin Core software project. The clients you're referring to are more suited I think for bitcoin.org which is a general website about Bitcoin. You can find their github at github.com/bitcoin-dot-org/bitcoin.org

Regarding the node js application, that's more for @laanwj, but afaik, the bitcoin-core github org is mostly for things relating directly to the Bitcoin Core project including dependencies for the main project. It appears to have it's home already at https://github.com/freewil/node-bitcoin. Again, I'll defer to @laanwj 

Thanks for your enquiry!

**Comment by MarcoFalke** [comment]
Imo, if bitcoincore.org includes links to rpc wrappers, it would looks
like an endorsement, which is something I am not aware we are doing.

Also, the wrapper seems to work as well with clients that are forked
from bitcoin core and kept the same rpc interface, so I think limiting
it to Bitcoin Core is not useful.

**Comment by ruimarinho** [comment]
Ok, thanks for your feedback. Do you have any interest at all in hosting that wrapper under the bitcoin-core github org even if that would require a no endorsement disclaimer? This would be similar to what Google does with some of its projects, like [WALT](https://github.com/google/walt/blob/master/README.md). The idea of the code donation is to foster discoverability, not changing responsibilities.
