### ISSUE TITLE
Show node adoption

### ISSUE THREAD

**Issue by lichtamberg** [bitcoin-core/bitcoincore.org#331]
Could you maybe add the node stats to the segwit adoption page? 

https://bitnodes.21.co/nodes/

I think it's worth to notice that already more than 60% of the community nodes want to run segwit!

**Comment by btcdrak** [comment]
btw, https://bitnodes.21.co/nodes/?q=NODE_WITNESS will show all witness nodes regardless of useragent.

Bitnodes only shows listening nodes, all nodes by crawler can be found here http://luke.dashjr.org/programs/bitcoin/files/charts/services.html (the site has been false reported to Google as compromised when it is not). But from this you can see the number is much higher.

The problem with absolute node count is it's meaningless. I find it more interesting that each Core release shows a steady increase conversion of _existing_ nodes from older to newer versions. That's certainly a lot more robust than a bunch of new nodes appearing out of nowhere, but still not very satisfactory.

https://bitnodes.21.co/dashboard/?days=365

**Comment by harding** [comment]
It additions to the concerns about node counts raised by @btcdrak in the preceding comment, the segwit support page was removed in PR #518, so I'm going to close this issue.
