### ISSUE TITLE
Error reading from data base, shutting down.

### ISSUE THREAD

**Issue by gillug** [bitcoin-core/bitcoincore.org#333]
Hello , please can some one help me for the Error reading from data base, shutting down. i was just 12 week behind sync. but this error coming again again , i have already re installed the bitcore-qt also data base backup also after the error is same.

**Comment by btcdrak** [comment]
I am sorry, this is not the place for support. Please visit bitcoin.stackexchange.com or as in #bitcoin on freenode IRC.

**Comment by VLADDIGBY** [comment]
Let me know if I  can be of any use. We are update with Bitcoincore and have full block chain 64 and 32 bit on an external hard drive. Not going in to to much detail we're on 0.21 I believe there is a 0.2.2 Chain now although I do not think it makes much difference I am slowly changing over testing on another device. All the best.

**Comment by VLADDIGBY** [comment]
I have 100's of downloaded zip files of various merges/forks overall projects.
