### ISSUE TITLE
Bitcoin Hardfork research documentation

### ISSUE THREAD

**Issue by FrancisPouliot** [bitcoin-core/bitcoincore.org#335]
Just found out about https://bitcoinhardforkresearch.github.io/ 

Since all that research is done by Bitcoin Core contributors, seems logical that it would be linked from bitcoincore.org

Possibly, could create a "Additional ressources" page for content not directly contributed by the bitcoincore.org contributors?

**Comment by MarcoFalke** [comment]
Tend toward NACK. The website should be solely used to provide a download link for the software.

Should be closed.

**Comment by laanwj** [comment]
Agree…
