### ISSUE TITLE
Source units available

### ISSUE THREAD

**Issue by Denis7000** [bitcoin-core/bitcoincore.org#336]
All the good and positive
please tell me what is the problem
hanging for a week and can not sync
He writes - Source units available
How is it treated?
Thanks to all
![image](https://cloud.githubusercontent.com/assets/25794671/22976156/976bd79a-f39a-11e6-8c8a-b9158a99ef79.png)

**Comment by MarcoFalke** [comment]
​It can take several weeks on weak hardware to sync the whole blockchain
from scratch.

For 0.14 we have reworked how to display the time remaining until the
initial block download is complete. For 0.13 the only indicator is the
progress bar in the status bar.​

**Comment by Denis7000** [comment]
Many thanks

**Comment by laanwj** [comment]
"Source units unavailable" sounds like "No block source available...", which used to be the message while not connected to a peer yet. If it's completely stuck that sounds like a network problem?

**Comment by Denis7000** [comment]
laanwj , Yes, it seems the problem with the network
those Internet priozheniya all work perfectly and that "suffocate" I suspected our local secret services because they do not want this to Projects developed in Belarus
And how can you check on what ports goes synchronization maybe they are banned or worse provider at a local pit mix everything on the firewall
Once again, thank you so much for assisting Guys
