### ISSUE TITLE
Add FAQ/Initial Block Download

### ISSUE THREAD

**Issue by paveljanik** [bitcoin-core/bitcoincore.org#349]
It would be handy to have a FAQ/IBD menu entry on the web so we can redirect people when asking why Bitcoin Core GUI is not doing anything on the first run, why it is consuming 100% CPU and IO at the first run etc.

**Comment by laanwj** [comment]
I think a FAQ is a good idea, but we should avoid duplicating bitcoin.org.

There's e.g.: https://bitcoin.org/en/full-node a guide about running a full node, which should mention this.

**Comment by paveljanik** [comment]
Yup, reported as https://github.com/bitcoin-dot-org/bitcoin.org/issues/1633, closing this one.
