### ISSUE TITLE
Add responsible disclosure policy

### ISSUE THREAD

**Issue by patwhite** [bitcoin-core/bitcoincore.org#432]
After controversy over UTXO attack and disclosure, would be worth having a well articulated responsible disclosure policy, for instance template available at: 

https://github.com/bugcrowd/disclosure-policy/blob/master/responsible_disclosure_policy.md

Only saw a brief mention of responsible disclosure at https://bitcoin.org/en/bitcoin-core/contribute/issues#disclosure (I know, different website), but all it did was reference the contact us page. The above template actually includes timelines (90 days), etc. Might not have helped in this case, but would at least provide a basis discussing disclosure.

**Comment by MarcoFalke** [comment]
There is https://bitcoincore.org/en/contact/ and https://github.com/bitcoin/bitcoin/security
