### ISSUE TITLE
cadena de bloques

### ISSUE THREAD

**Issue by javiertuerca** [bitcoin-core/bitcoincore.org#465]
buenos días:
 E seguido el desarrollo de Bitcoin desde hace mas de un año y viendo como el nodo completo asciende a mas de 140 GB y teniendo en cuenta que las personas promedio tienen una pc con 1 TB ,con el aumento de la popularidad de Bitcoin las transacciones aumentaran rápidamente y por lo tanto los nodos ,dejando de lado a estas personas y disminuyendo la red de nodos que en la actualidad llegan a 12.000 aproximadamente.
Mi propuesta es agregar nodos  divididos  en cadenas de bloques  y así poder disminuir la capacidad de un nodo ,y que todos puedan acceder a un nodo parcial  , esto aumentaría las descargas de nodos divididos en partes iguales 1,2,3 o 4 ,resumiendo 4 computadoras con menos de 1 TB  de capacidad podrían crear un nodo completo y combinar con las cpu de nodos completos ,en cuanto a los mineros creo que no resultara difícil, poder acceder a los diferentes nodos para poder verificar las transacciones
muchas gracias y espero poder colaborar con la red

**Comment by jnewbery** [comment]
Hi Javier. I don't speak Spanish, but I think I understand enough. You may be interested in pruned nodes. I recommend you take a look at the `-prune` option on bitcoind.

This is an issue tracker for the bitcoincore.org website, not a technical support forum. I suggest you use the #bitcoin IRC channel or Bitcoin stack exchange if you have technical questions.
