### ISSUE TITLE
Lost bitcoin adresses

### ISSUE THREAD

**Issue by RichardTingen** [bitcoin-core/bitcoincore.org#467]
Hello,

Has anyone experience with Bitcoin Core? I tried to install it on my PC, and created bitcoin-addresses to collect bitcoins. My computer crashed and I already used these addresses. Now I cannot get back the used bitcoin-addresses.  Does nyone know how I can get back the missing addresses?

**Comment by jnewbery** [comment]
This is an issue tracker for the bitcoincore.org website, not a technical support forum for Bitcoin.

You may find some nice people to help you at IRC #bitcoin or Bitcoin stack exchange.

**Comment by jonasschnelli** [comment]
What @jnewbery said.
Closing.
