### ISSUE TITLE
No portuguese(PT-BR) translation avalaible on transifex

### ISSUE THREAD

**Issue by pedddro** [bitcoin-core/bitcoincore.org#472]
Please, have a look at it, when requesting a new idiom, portuguese PT-BR dont show on the options, then i cant start a translation.
![portuguese core](https://user-images.githubusercontent.com/18357571/33465769-c91b70a6-d630-11e7-9361-4f092de13951.png)

**Comment by MarcoFalke** [comment]
This project doesn't use transifex. Can be closed
