### ISSUE TITLE
Recent posts not show dates

### ISSUE THREAD

**Issue by ghost** [bitcoin-core/bitcoincore.org#488]
Recent posts should always have a timestamp.

<img width="665" alt="screen shot 2017-12-27 at 1 20 56 pm" src="https://user-images.githubusercontent.com/440298/34371515-7af7b39a-ea93-11e7-8cd2-7a487a592457.png">

**Comment by jonasschnelli** [comment]
Agree... this should be fixed.

**Comment by Daniel-Leedan** [comment]
@jonasschnelli Still relevant? I'm willing to spend some time looking into it.

**Comment by JijoBose** [comment]
@jonasschnelli Let me know if the above PR solves the issue 😄
