### ISSUE TITLE
"Bitcoin" name changed to "Bitcoin Core" (YES it IS a BUG)

### ISSUE THREAD

**Issue by MyS5Droid** [bitcoin-core/bitcoincore.org#510]
Bitcoin should immediately revert back to it's ORIGINAL name, "Bitcoin" and publicly rebuke the name "Bitcoin Core".

Using the name "Bitcoin Core" adds confusion, and new crypto investors will wonder where bitcoin is because all they see is "bitcoin core" and will then assume that Roger Ver is right and BCH is the "true bitcoin"

New investors are looking for "Bitcoin" not "Bitcoin Core", causing confusion. They will assume that Roger Ver is right that "Bitcoin Core" is a FORK of bitcoin, and that bitcoin is now bitcoin cash...

The story put out should be clear: "THIS IS BITCOIN, and ALL OTHERS ARE FORKS CREATED BY RANDOM PEOPLE with NOTHING to do with BITCOIN"

This is easiest done keeping Bitcoin's original name and reputation, and publicly stating that BCH has NOTHING to do with Bitcoin and is just a snapshot of old source code taken just before the best improvements were made by GREEDY people who thought they could rip off Bitcoin's name - and until the name reverts back, you are all helping them!

I do not support this name change. Anyone who truly loves Bitcoin will not either.

**Comment by achow101** [comment]
Bitcoin Core is the name of a software, not the coin. We don't call coins by the name of the reference implementation (unless you are Roger Ver, and only for Bitcoin). People don't call Bitcoin Cash "Bitcoin ABC" even though its reference implementation is Bitcoin ABC.
