### ISSUE TITLE
Add documentation about generated javascript

### ISSUE THREAD

**Issue by karel-3d** [bitcoin-core/bitcoincore.org#525]
Jekyll does not generate the minified javascript; it was generated in the initial commit and the process is not documented.

(It is questionable if the javascript even needs to be minified, since the size difference is minimal in this case.)

**Comment by harding** [comment]
I agree that we should have a non-minified copy of the JS in the repository for review (if necessary for optimization, we can minify it at compile time).  I believe the origin of the version we use is from an older version of the [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/) Jekyll theme in case anyone wanted to look into it.  (If not, I'll investigate myself when I get a chance.)
