### ISSUE TITLE
Add signature to Capacity Increase Roadmap 2015-12-21

### ISSUE THREAD

**Issue by btcdrak** [bitcoin-core/bitcoincore.org#53]
If you would like to add your signature in support of the [Capacity Increase Roadmap 2015-12-21](https://bitcoincore.org/en/2015/12/21/capacity-increase/) page on the bitcoincore.org website, please add your name and company and position if applicable in a comment below. If support is from the company as a whole please make that clear.

For discussion, please visit the [Bitcoin Core Slack group](https://bitcoincore.slack.com/) rather than this ticket. To sign up, visit [here](https://slack.bitcoincore.org).

**Comment by carnesen** [comment]
Chris Arnesen (individual)

**Comment by shangzhou** [comment]
Shangzhou Wu (individual)

**Comment by lucayepa** [comment]
ACK statement

**Comment by btcdrak** [comment]
Updated in 59ce012

**Comment by apoelstra** [comment]
Andrew Poelstra

**Comment by psztorc** [comment]
Paul Sztorc

**Comment by bityogi** [comment]
Kawal Singh

**Comment by btcdrak** [comment]
updated in feadea60d3d86ab1a27671a8b1e130b584c23773

**Comment by maaku** [comment]
Please remove "For more information, please see the FAQ." The FAQ was not signed by all the signatories.

**Comment by CyrusV5** [comment]
Cyrus, Bitcointalk moderator.

**Comment by lecr01** [comment]
Luis Cardenas System Programmer Mercoeso  (socialist electronic community market) Development of electronic commerce applications under IBM I series platform with use of bitcoin and own blockchain for poor families.
