### ISSUE TITLE
Urgent Help I load Bitcoin and Show Wallet out of sync

### ISSUE THREAD

**Issue by Daniel114400** [bitcoin-core/bitcoincore.org#530]
i need help i load money on my Bitcoin Core for more than 4 hours now and the money is not display on my Bitcoin Core what i only see is wallet out of sync i need help please what can i do to get my bitcoin available to use

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the bitcoincore.org page repository. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
