### ISSUE TITLE
snycronizing

### ISSUE THREAD

**Issue by doone57** [bitcoin-core/bitcoincore.org#566]
Bitcoin Core has been syncronizinf for months I need help , I have transactions that need done

**Comment by MarcoFalke** [comment]
No need to open more than one issue https://github.com/bitcoin/bitcoin/issues/13504#issuecomment-398443803

This should be closed

**Comment by doone57** [comment]
Bitcoin Core has been syncronizinf for months I need help , I have transactions that need done

**Comment by karel-3d** [comment]
Hello, this repository is for the website, not for the software.

**Comment by doone57** [comment]
how do i get support for the website

    On Tuesday, June 19, 2018, 11:52:57 AM EDT, Karel Bílek <notifications@github.com> wrote:  
 
 
Hello, this repository is for the website, not for the software.
