### ISSUE TITLE
Replaying 0%

### ISSUE THREAD

**Issue by Upset3** [bitcoin-core/bitcoincore.org#594]
So two days ago my Bitcoin Core was working fine.  Last night it was trying to load but it just kept at 0% when it was replaying blocks.  So I updated it thinking that will help but it still says the same thing.  What else can I do to get back into it to be able to access my bitcoin?

**Comment by hancoin** [comment]
What did you update? Go to your app data file, bitcoin folder, erase everything except for your wallet.dat and reopen the wallet. Or try putting everything on a different drive. You probably messed with some computer setting that effected the blockchain sync, maybe im wrong im not that experienced.. well, sort of... ive been subscribed to this thread a while, this is my first comment. Hope it helps

**Comment by Upset3** [comment]
I updated bitcoin core, and I will try that and let u know how it went.  When I'm back to my computer.

**Comment by hancoin** [comment]
sure let me know, im curious to see if im at all of any use to the bitcoin community ^ . ^

**Comment by Upset3** [comment]
I thank you for your help and I want to try what you suggest, but for some unknown reason it works now that I'm back to my computer.

**Comment by hancoin** [comment]
Oh nice good for you. :D

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by karel-3d** [comment]
This is a bug tracker for bitcoincore.org website, not for the software.

**Comment by jnewbery** [comment]
As karel-3d says, this is an issue tracker for the bitcoincore.org website.

For end-user support, you should use the Freenode #bitcoin channel or stack exchange (not https://github.com/bitcoin/bitcoin/ since that's an issue tracker for the Bitcoin Core software)
