### ISSUE TITLE
Is the sponsorship programme still alive?

### ISSUE THREAD

**Issue by karel-3d** [bitcoin-core/bitcoincore.org#607]
I have randomly stumbled on this sub-page on bitcoin core website.

* https://bitcoincore.org/en/about/sponsorship/programme/
* https://bitcoincore.org/en/about/sponsorship/faq/
* https://bitcoincore.org/en/2016/04/04/announcing_sponsorship_programme/

These webpages have been around since 2016, but I have not seen any wide coverage of them and I haven't heard about anyone participating, or any news.

Is the programme still alive?

**Comment by harding** [comment]
I was hoping someone else with more information would comment on this issue.  I don't have any information and I haven't heard of any activity being funded through the program.  If the program is actively funding any efforts, we should probably do a better job of publicizing that.

**Comment by jnewbery** [comment]
I don't know anything about these programs. Perhaps @btcdrak does?

These pages were added without a PR or discussion, so it's difficult to excavate the history around them. It seems to me that the programme was launched with good intentions, but fundraising and matching sponsors to developers seems like a hard thing to maintain, and probably outside the scope of what Bitcoin Core should be doing. Without the historic record of why these pages were added, it's difficult to know the rationale.

@laanwj, @jonasschnelli - anything to add here?

**Comment by luke-jr** [comment]
I haven't directly seen any funding from this programme, but perhaps it is a source of funds used for coredev.tech meetings? I'm not really sure.

**Comment by MarcoFalke** [comment]
I don't know if this program is still alive, but lately many companies have directly hired (and thus sponsored) developers to work full-time on Bitcoin Core or related technologies.

**Comment by moneyball** [comment]
Should this page be removed if it isn't accurate or active? Alternatively, what do people think about linking to organizations that hire or sponsor Core development, or are actively seeking to do so?

**Comment by MarcoFalke** [comment]
@moneyball Sounds good to me!

**Comment by harding** [comment]
+1 on removing the page.  I'm meh on linking to organizations that sponsor Core dev for the same reason that we previously removed the page about Core developers.

**Comment by jnewbery** [comment]
Concept ACK removing the sponsorship pages

**Comment by MarcoFalke** [comment]
Would Bitcoin Ops be a more appropriate place for the page? They appear like the glue between protocol development and organizations.

**Comment by jnewbery** [comment]
> Would Bitcoin Ops be a more appropriate place for the page? They appear like the glue between protocol development and organizations.

We don't want to be seen as 'the glue'. We try to improve communications between the open-source community and Bitcoin businesses, but we're very conscious of not letting our scope creep and becoming some kind of Bitcoin foundation.

I'll raise this internally, but I expect it's not something that we want to take on.

**Comment by laanwj** [comment]
Closed by #657
