### ISSUE TITLE
Sandy link not working

### ISSUE THREAD

**Issue by lucayepa** [bitcoin-core/bitcoincore.org#645]
The link to sandy seems wrong, or sandy is down.

To reproduce, just try to add an email in https://bitcoincore.org/en/list/announcements/join/

**Comment by MarcoFalke** [comment]
Uff, this site should be updated to point to the `bitcoin-core-dev` mailing list

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by harding** [comment]
Fixed by #610
