### ISSUE TITLE
Adding LocalCoinSwap to P2P exchanges

### ISSUE THREAD

**Issue by goldiblocks** [bitcoin-core/bitcoincore.org#652]
Is it possible to add LocalCoinSwap (https://localcoinswap.com) to the following page: 

https://bitcoin.org/en/exchanges#p2p

LocalCoinSwap is one of the only P2P platforms that still works with people from all around the world to buy and sell Bitcoin without requiring KYC.

**Comment by jnewbery** [comment]
Wrong repo. This is the repo for bitcoincore.org. You want https://github.com/bitcoin-dot-org/bitcoin.org.
