### ISSUE TITLE
raw transaction

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [bitcoin-core/bitcoincore.org#663]
Could you please point out the library responsible for filling "vin" or input parameter in raw transaction.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core website. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
