### ISSUE TITLE
Mitigate DOSing of GPG keys on public key infrastructure

### ISSUE THREAD

**Issue by Xekyo** [bitcoin-core/bitcoincore.org#664]
Is there any fallback in place for Bitcoin Core to distribute the signing key in case of it being poisoned on public infrastructure? 

I saw that #550 removed previously directly linked keys, presumably to prevent revocations from not being seen when people trust the keys on github or this website. 

However, we've seen multiple other projects becoming inaccessible due to key poisoning attacks, so we might want to have the signing keys and gitian-keys available outside of public key infrastructure somewhere as well.

**Comment by harding** [comment]
They key is still available in the repo and is on the server here: https://bitcoincore.org/keys/laanwj-releases.asc.  We can directly link to it again if necessary.
