### ISSUE TITLE
Issue importing signing key on MacOS

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/bitcoincore.org#667]
I'm teaching a class about using walllets this week. Multiple people have encountered an issue with steps 6 & 7 of the MacOS instructions:

```
$ gpg --recv-keys 01EA5486DE18A882D4C2684590C8019E36C2E964
gpg: key 90C8019E36C2E964: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1

$ gpg --verify SHA256SUMS.asc
gpg: Signature made Fri Aug  9 16:08:43 2019 KST
gpg:                using RSA key 90C8019E36C2E964
gpg: Can't check signature: No public key
```

I don't know exactly what this `new key but contains no user ID` means, and don't own a Mac to attempt to debug it. 

We've fixed it by using ubuntu's keyserver:

```
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 01EA5486DE18A882D4C2684590C8019E36C2E964
```

**Comment by watwood** [comment]
Cool. How can I attend?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
