### ISSUE TITLE
Share "Windows verification instructions" Link

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/bitcoincore.org#668]
If would be nice if this HTML element on [the download page](https://bitcoincore.org/en/download/) had an ID (e.g. `id="windows-verification-instructions"`) so that I could share a link to specifically that part of the instructions: e.g. https://bitcoincore.org/en/download/#windows-verification-instructions
![windows-verification-link](https://user-images.githubusercontent.com/4335621/63713818-0625a480-c806-11e9-8e4f-86e16da7f74e.png)

(same for other platforms, just using windows as an example)

**Comment by justinmoon** [comment]
That's be great

**Comment by harding** [comment]
Fixed in #669 .  The link is https://bitcoincore.org/en/download#verify-your-download
