### ISSUE TITLE
Delete unused transifex project

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoincore.org#670]
There is a project on transifex, which is unused according to https://github.com/bitcoin/bitcoin/issues/16754#issuecomment-526373630. Thus, it should be deleted or deactivated to not waste translators time.

https://www.transifex.com/bitcoincore/bitcoincoreorg/dashboard/

**Comment by harding** [comment]
Yes, please delete/deactivate.  I don't have access to delete the project on transifex, so I'm assigning to @laanwj

**Comment by laanwj** [comment]
Done
