### ISSUE TITLE
What do I do when I get to end of blockchain data outputs "warning 52 of last 100 blocks have unexpected version"?

### ISSUE THREAD

**Issue by Redalio** [bitcoin-core/bitcoincore.org#674]
I am stuck when get to "warning 52 of last 100 blocks have unexpected version"! What command do I use to get rid of this on the next round of blockchain dat download?!?!

This issue tracker is for issues with the Bitcoin Core project website at
[bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

**Comment by jnewbery** [comment]
Hi @Redalio . This issue tracker is for issues with the Bitcoin Core project website at bitcoincore.org.

General bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange at https://bitcoin.stackexchange.com.

Someone has already asked your question here: https://bitcoin.stackexchange.com/questions/46318/bitcond-v0-12-1-updatetip-6-of-last-100-blocks-have-unexpected-version
