### ISSUE TITLE
Invalid cert in links in segwit wallet dev guide

### ISSUE THREAD

**Issue by kanzure** [bitcoin-core/bitcoincore.org#692]
The links to the n.bitcoin.ninja block explorer have invalid certs: https://bitcoincore.org/en/segwit_wallet_dev

probably need to switch to some other flavor-of-the-day block explorer

**Comment by TheBlueMatt** [comment]
@NicolasDorier

**Comment by NicolasDorier** [comment]
I completely forgot this server... trying to find where I can access it.

**Comment by Binh0103** [comment]
@kanzure @TheBlueMatt @NicolasDorier @harding @
