### ISSUE TITLE
Late Transactoin

### ISSUE THREAD

**Issue by w3bst3r67** [bitcoin-core/bitcoincore.org#709]
I Transfered 0.0126000 after fee Bitcoin from a crypto.com wallet to my Bitcoincore.org wallet address:-  1AKWvdsoAQC43sBANr9pCnk74nHCdrAvB6.
This was on the 07/07/2020, the tansaction is sitting on the blockchain as unspent.
The block has confirmed, is it a case of waiting for it to be received, or is it more serious??,

Can someone help me please

**Comment by MarcoFalke** [comment]
Have you synced your node to the chain?

Regardless, the issue tracker is used to track technical issues related to the Bitcoin Core website. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by w3bst3r67** [comment]
If you mean reset blockchain then yes, it is not very on where to get support for this app, it's been 4 days now, and no one can help, it's a lot of money to me if not for anybody else. Is there a dedicated channel I can go down, because every line I have tried so far has come to nothing.


Not very good at sorry to bother you.




On Sun, Jul 12, 2020 at 3:01 PM +0100, "MarcoFalke" <notifications@github.com> wrote:















Have you synced your node to the chain?


Regardless, the issue tracker is used to track technical issues related to the Bitcoin Core website. Keep in mind that general bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange or the #bitcoin IRC channel on freenode.

**Comment by w3bst3r67** [comment]
Thanks




Sent from Samsung Mobile on O2


Get Outlook for Android







On Sun, Jul 12, 2020 at 3:30 PM +0100, "David A. Harding" <notifications@github.com> wrote:















Closed #709.
