### ISSUE TITLE
Transaction not received

### ISSUE THREAD

**Issue by w3bst3r67** [bitcoin-core/bitcoincore.org#710]
I moved 0.013mBTC from a Crypto.com wallet to the Bitcoincore.org wallet. The transaction never got into the wallet despite being confirmed on the blockchain. The transaction is there 0.126mBTC after fee. 
Hash :- 13290114c5e1fe381c707e5f67b246cd0260f5bd24c9a1fc1aed0eab08dd2521
Address
1AKWvdsoAQC43sBANr9pCnk74nHCdrAvB6
As far as Crypto are concerned the transaction has reached the address.
Why has it not pulled through in to the wallet. Can someone please help.

**Comment by MarcoFalke** [comment]
Is your node synced?

Regardless,  the issue tracker is used to track technical issues related to the Bitcoin Core website. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by WorldBosss1** [comment]
Please call me 2037153179. Someone hacked my email and is emailing you from my account. My name is dean freer. They are hacking binance i believe as well. Please call me back

**Comment by w3bst3r67** [comment]
> Is your node synced?
> 
> Regardless,  the issue tracker is used to track technical issues related to the Bitcoin Core website. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

Yes, I synced it twice since the 07/07/2020

**Comment by w3bst3r67** [comment]
Still not been able to do anything with it, some have said that I do not have the private key that generated the address.
It was generated by the by the Bitcoin core wallet I used for the second transaction in my wallet the third did not come in to the wallet with the same address.
Can someone take a look, I am at a loss. I know I haven't lost because I can see it on the block chain, but I can't access it.
How do I use the address of the third transaction to receive?

**Comment by harding** [comment]
> general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by w3bst3r67** [comment]
So the Bitcoin core app developers have nothing to do with the issues with the app itself, the address was generated by the app but the transaction has pulled through the app. It is on the blockchain with the other two transactions. Why has it not appeared in the Bitcoin core app?


Is there anyway the developers can check to see if there anything wrong with the app?




Sent from Samsung Mobile on O2


Get Outlook for Android







On Wed, Aug 5, 2020 at 8:16 PM +0100, "David A. Harding" <notifications@github.com> wrote:
















general bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange or the #bitcoin IRC channel on freenode.
