### ISSUE TITLE
Blockchain downloading endless

### ISSUE THREAD

**Issue by svpi11** [bitcoin-core/bitcoincore.org#715]
I cannot download the blockchain fully :( 
My computer is always going becoming hot and noisy and finishing by just crashing, then I have to download the blockchain again from the begining... Endless process 😞😩

**Comment by harding** [comment]
I'm sorry to hear that.  You may find [these instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-memory.md) helpful at reducing the burden on your computer.  This issue tracker isn't for support, so if you have any follow-up questions, please ask them on https://bitcoin.stackexchange.com/ or on the `#bitcoin` channel on https://freenode.net/ 

Good luck!

**Comment by svpi11** [comment]
Thanks for the help :)
