### ISSUE TITLE
About: outdated contributors link

### ISSUE THREAD

**Issue by ipriver** [bitcoin-core/bitcoincore.org#718]
There's an outdated query link that can be found on [**About** page](https://bitcoincore.org/en/about/) in **Contributors** section `A list of code contributors for the last year can be found on Github.` that links to `https://github.com/bitcoin/bitcoin/graphs/contributors?from=2017-03-01`

The link hasn't been updated since 2017. 

It could be either updated to 2019 or the text can be modified to `A list of code contributors can be found on Github.` and `?from` query removed from the url to prevent any issues in the future.

**Comment by harding** [comment]
@ipriver Thanks; opened #719 to fix this.
