### ISSUE TITLE
Add Onion-Location header

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/bitcoincore.org#720]
Adding an `Onion-Location: http://6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion/` header would help people find the onion address of the hidden service for the site more easily.

See https://community.torproject.org/onion-services/advanced/onion-location/

**Comment by TheBlueMatt** [comment]
#706.

**Comment by laanwj** [comment]
Strange, I searched for previous onion issues and couldn't find one.

**Comment by RiccardoMasutti** [comment]
> Strange, I searched for previous onion issues and couldn't find one.

Because I didn't create an issue about it but just the PR
