### ISSUE TITLE
Downloads proceed rapidly, then stall

### ISSUE THREAD

**Issue by Empact** [bitcoin-core/bitcoincore.org#753]
On downloading 0.21 from https://bitcoincore.org/bin/bitcoin-core-0.21.0/ I observed the following behavior: the download would proceed rapidly for the first N mbs, then stall in a pending state without progress.

If I cancelled the download, then restarted it, it would continue rapidly from where it had left off. A few iterations of this were necessary to download.

This was via Chrome on macOS.

**Comment by harding** [comment]
Just tested https://bitcoincore.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-x86_64-linux-gnu.tar.gz using Firefox on Debian GNU/Linux via my local ISP and one of my VPS's connection, and both downloaded at a constant speed that is normal for that connection.

**Comment by TheBlueMatt** [comment]
This isn’t really enough to debug. Most likely it’s an issue from your connection or ISP to the site, but if you could manually test and capture a pcap (to both of the two IPs the site resolves to separately), as well as provide mtrs to both of the two sites, I could take a look.

**Comment by Empact** [comment]
Working fine for me now. I guess a network issue or the like. Thanks!

**Comment by WorldBosss1** [comment]
Ok. There must be a node.js for example or something thats not correct with coding. Keep me in mind. I can fix for you. How much are you offering for a fix?

**Comment by MarcoFalke** [comment]
I am running into this from time to time, and it seems others are, too: https://github.com/bitcoin/bitcoin/pull/20354#issuecomment-879191692

**Comment by MarcoFalke** [comment]
Happy to debug this if there is a command I can copy-paste into my terminal

**Comment by NelsonGaldeman** [comment]
Not sure if it helps much but here are the console logs from when it failed for me.

```Releases directory: releases
Fetching: https://bitcoincore.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-osx64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 25.1M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.1M  100 25.1M    0     0  2281k      0  0:00:11  0:00:11 --:--:-- 2336k
Checksum did not match
```

I'm able to reproduce it atm (tried a couple of times). Only for 0.21.0, others work just fine. I'm using `python3 test/get_previous_releases.py -b v0.21.0` from this commit fa80e10d94dbf86da84fc761b09fb631155a5b25 running on OSX.

I ran `tcpdump -i en0 -s 65535 -w packet_log.txt` and here is the output file
https://wetransfer.com/downloads/ff0a909c17d57fadf6e0b9fb43c2554a20210713172224/8741907aa34a1006d96c33775964237920210713172248/195b7c

Traceroute
```
➜  /Users/nelson/Documents/chaincode/bitcoin (pr20354) ✗  traceroute bitcoincore.org
traceroute: Warning: bitcoincore.org has multiple addresses; using 198.251.83.116
traceroute to bitcoincore.org (198.251.83.116), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  9.153 ms  1.745 ms  1.519 ms
 2  nowtvhub.home (192.168.0.1)  2.014 ms  3.030 ms  1.852 ms
 3  * * *
 4  be431.pr3.enlba.isp.sky.com (2.120.9.184)  26.958 ms
    be431.pr2.hobir.isp.sky.com (2.120.9.182)  14.603 ms  14.687 ms
 5  02780e0b.bb.sky.com (2.120.14.11)  19.111 ms
    02780e09.bb.sky.com (2.120.14.9)  17.148 ms
    02780e0b.bb.sky.com (2.120.14.11)  19.364 ms
 6  ldn-bb4-link.ip.twelve99.net (62.115.117.122)  24.312 ms
    ldn-bb1-link.ip.twelve99.net (62.115.117.192)  21.159 ms  22.377 ms
 7  ldn-b2-link.ip.twelve99.net (62.115.120.239)  25.418 ms  25.351 ms  19.905 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
```

If it actually only happens on a specific version It should not be a networking issue, should it?

**Comment by TheBlueMatt** [comment]
A checksum mismatch after what appears to be a 100% download is definitely not the same as the the download stalling and then timing out. Can you open a new issue for that? What is the expected checksum of that file? Is it `695fb624fa6423f5da4f443b60763dd1d77488bfe5ef63760904a7b54e91298d`?

**Comment by TheBlueMatt** [comment]
> Happy to debug this if there is a command I can copy-paste into my terminal

If you have a time-out issue, can you provide a traceroute/mtr to the specific IP which is timing out (there are multiple IPs for bitcoincore.org, please let me know if you see the issue for all of them, or only one). A `tcpdump -w file.pcap` of the event would also be helpful, as Nelson provided.

**Comment by TheBlueMatt** [comment]
> Fetching: https://bitcoincore.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-osx64.tar.gz

I'm a bit confused, the linked PR does not have a checksum for 0.21, it appears to only be adding checksums/fetching 0.20.1

**Comment by NelsonGaldeman** [comment]
> > Fetching: https://bitcoincore.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-osx64.tar.gz
> 
> I'm a bit confused, the linked PR does not have a checksum for 0.21, it appears to only be adding checksums/fetching 0.20.1

You are right that's it, it's not a checksum mismatch it's that the hash isn't there! Thank you.

**Comment by NelsonGaldeman** [comment]
> I'm a bit confused, the linked PR does not have a checksum for 0.21, it appears to only be adding checksums/fetching 0.20.1

You are right that's it, it's not a checksum mismatch! It just doesn't exist. The message scares you a little bit, didn't consider it wouldn't exist! Thank you. 

Added a message saying there is no checksum to compare against explicitly instead of "_mismatch_" https://github.com/bitcoin/bitcoin/pull/22442

**Comment by MarcoFalke** [comment]
Ok, so it wasn't a download issue after all? I assumed a difference in the file size hints at a download issue.

>  "Checked both files size showed on the console and they were slightly different" (https://github.com/bitcoin/bitcoin/pull/20354#issuecomment-879191692)

Locally (when using `wget`) I observed different download speeds. Sometimes the download uses the full available capacity, sometimes it appears to be throttled at 200 KB/s, sometimes it timed out. Whenever I ran into a checksum mismatch, I saw that the filesize differed as well.

It is certainly possible that the issue is with my Laptop or my ISP, which is why I never reported the issue previously.

**Comment by TheBlueMatt** [comment]
> Ok, so it wasn't a download issue after all? I assumed a difference in the file size hints at a download issue.

In this case, no, it was not.

> Locally (when using wget) I observed different download speeds. Sometimes the download uses the full available capacity, sometimes it appears to be throttled at 200 KB/s, sometimes it timed out. Whenever I ran into a checksum mismatch, I saw that the filesize differed as well.

Different download speeds could totally be reasonable, but it shouldn't be throttled or too low, if you get a checksum mismatch or the connection completely hanging, though, I'd like to know.

> It is certainly possible that the issue is with my Laptop or my ISP, which is why I never reported the issue previously.

If there's actually a checksum mismatch, that's a really, really, really critical problem. Please don't skip reporting just cause it "could" be your internet being slow!

**Comment by MarcoFalke** [comment]
Thinking more about this, one possibility why I saw different checksums:
* Start `wget`
* After some minutes, realize the download has stalled at 0 B/s. Press `^C`, and restart `wget`
* End up with two files `...tar.gz` (truncated file, incorrect hashsum) and `...tar.gz.1` (full file)

I think this issue can be closed again. I'll open a new issue the next time I see a checksum mismatch. I'll comment on this issue the next time I see a stalling download.

**Comment by MarcoFalke** [comment]
@harding @laanwj I think this can be closed

**Comment by MarcoFalke** [comment]
This still happens intermittently. Obviously not reproducible, even with the same IP. Since it is not reproducible, it is also hard to start tcpdump to capture it. Though, this is the terminal output:

```
# wget https://bitcoincore.org/bin/bitcoin-core-0.14.3/bitcoin-0.14.3-osx64.tar.gz
--2022-02-02 18:11:15--  https://bitcoincore.org/bin/bitcoin-core-0.14.3/bitcoin-0.14.3-osx64.tar.gz
Resolving bitcoincore.org (bitcoincore.org)... 107.191.99.5, 198.251.83.116
Connecting to bitcoincore.org (bitcoincore.org)|107.191.99.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19643239 (19M) [application/octet-stream]
Saving to: ‘bitcoin-0.14.3-osx64.tar.gz’

bitcoin-0.14.3-osx64.tar.gz                                   6%[========>                                                                                                                                 ]   1.30M  1.92MB/s               ^
bitcoin-0.14.3-osx64.tar.gz                                  19%[=========================>                                                                                                                ]   3.64M  1.23MB/s               ^
bitcoin-0.14.3-osx64.tar.gz                                  19%[=========================>                                                                                                                ]   3.64M  --.-KB/s    eta 24s    ^
bitcoin-0.14.3-osx64.tar.gz                                  19%[=========================>                                                                                                                ]   3.64M  --.-KB/s    eta 10m 8s ^
bitcoin-0.14.3-osx64.tar.gz                                  19%[=========================>                                                                                                                ]   3.64M  --.-KB/s    eta 10m 31s
^C
# ^C

**Comment by MarcoFalke** [comment]
Aaaand once more (in a docker, so I can't run tcpdump, even if I wanted to):

```
# wget https://bitcoincore.org/bin/bitcoin-core-0.14.3/bitcoin-0.14.3-x86_64-linux-gnu.tar.gz
--2022-02-02 18:57:53--  https://bitcoincore.org/bin/bitcoin-core-0.14.3/bitcoin-0.14.3-x86_64-linux-gnu.tar.gz
Resolving bitcoincore.org (bitcoincore.org)... 107.191.99.5, 198.251.83.116
Connecting to bitcoincore.org (bitcoincore.org)|107.191.99.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24644309 (24M) [application/octet-stream]
Saving to: ‘bitcoin-0.14.3-x86_64-linux-gnu.tar.gz’

bitcoin-0.14.3-x86_64-linux-gnu.tar.gz                       14%[==================>                                                                                                                       ]   3.36M  --.-KB/s    eta 2m 29s ^
bitcoin-0.14.3-x86_64-linux-gnu.tar.gz                       14%[==================>                                                                                                                       ]   3.36M  --.-KB/s    eta 4m 11s ^
bitcoin-0.14.3-x86_64-linux-gnu.tar.gz                       14%[==================>                                                                                                                       ]   3.36M  --.-KB/s    eta 6m 51s ^
bitcoin-0.14.3-x86_64-linux-gnu.tar.gz                       14%[==================>                                                                                                                       ]   3.36M  --.-KB/s    eta 7m 2s  
^C

**Comment by TheBlueMatt** [comment]
Can you provide a wireshark dump for when this happens, or an mtr?

**Comment by MarcoFalke** [comment]
mtr says something with "Loss", which probably means the box in my room is crap?

![Screenshot from 2022-02-02 20-46-35](https://user-images.githubusercontent.com/6399679/152226798-5c755bd0-b1cf-4ed8-8a31-20b5a5bbf958.png)

**Comment by TheBlueMatt** [comment]
No, that mtr shows no loss (loss that dissapears later just means icmp ratelimiting not "real" loss). I'd love to see a pcap for the actual download.
