### ISSUE TITLE
HIlfe Bei  der rücksendung

### ISSUE THREAD

**Issue by sb-immo** [bitcoin-core/bitcoincore.org#754]
This issue tracker is for issues with the Bitcoin Core project website at
[bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

**Comment by sb-immo** [comment]
Guten tag 

ich hab e vor jahren bitcoins gekauft und  auf ihre wallet  hinterlegt,,, jedoch komme ich nciht mehr  drauf. ich habe  die SID  und die ID  sowie passwort ncoh und  die zahlungswege sowie screenshorts   aber   es geht nicht mehr  ich bitte um  dringend hilfe

**Comment by sb-immo** [comment]
ich bitte um antwort und hilfe

**Comment by laanwj** [comment]
> General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

This issue tracker is for reporting issues with the web site, not for requesting help using bitcoin.
