### ISSUE TITLE
Code vom  jahr 2009  von bitcoin  alte wallet wiederherstellen

### ISSUE THREAD

**Issue by sb-immo** [bitcoin-core/bitcoincore.org#755]
This issue tracker is for issues with the Bitcoin Core project website at
[bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

**Comment by sb-immo** [comment]
Good day

 I don't have the wallet file anymore .. better said there is no more on it .. but i have the 31 digit e code and the transactions.

would that be helpful or feasible .. so I would ask, where can I wear this so that I can try it out and find out

**Comment by MarcoFalke** [comment]
Without the wallet.dat or the private keys you won't be able to restore the wallet.

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com or some other bitcoin forum.
