### ISSUE TITLE
Hacker can replace the important download files at bitcoincore.org hidden service via self-build tor exit node.

### ISSUE THREAD

**Issue by Bzvwf16WSDKoSZd8** [bitcoin-core/bitcoincore.org#756]
Reference:
https://support.torproject.org/https/https-1/

When only using tor, final tor node (exit node) or any people after this node, can see and modify all your data if you are not using tor with https to encrypting the traffic.

All files on this page are replaceable by hacker (include Bitcoin Core Release Signing Keys)
http://6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion/en/download/

Because bitcoincore.org hidden service still not using https

For example:
The protonmail hidden service force redirect all http requests to their https
http://protonirockerxow.onion/login --> https://protonirockerxow.onion/login

"bitcoincore.org" main site have completely done for this
http://bitcoincore.org/ --> https://bitcoincore.org/

This is a very serious vulnerability, because some people will not notice this when browsing tor site (They think they are safe).

**Comment by TheBlueMatt** [comment]
This is not true - onion addresses do not pass through exit nodes and there is no intermediary who has access to the unencrypted stream.

**Comment by harding** [comment]
Agree on this not being a vulnerability.

Looking at the ProtonMail hidden service site, it seems to me that the only advantage of them using a certificate is that they get their company name in the browser bar because they have an EV cert, which maybe gives visitors some extra confidence.  Since we don't have an EV cert for our primary domain, I can't see any advantage for us in adding a cert to the hidden service.

![2021-02-23-11_35_39_426312568](https://user-images.githubusercontent.com/61096/108911714-b75bf500-75cb-11eb-8e4d-285d9cd98216.png)

**Comment by Bzvwf16WSDKoSZd8** [comment]
> This is not true - onion addresses do not pass through exit nodes and there is no intermediary who has access to the unencrypted stream.

All tor traffic have pass through exit nodes finally, exit nodes may see all unencrypted stream.
![How_Tor_Works_2 svg](https://user-images.githubusercontent.com/46224228/108948477-85b35e80-769d-11eb-8999-28f3e4a64fa7.png)

**Comment by TheBlueMatt** [comment]
That is about regular traffic, not onion traffic. This issue should be closed.

**Comment by Bzvwf16WSDKoSZd8** [comment]
> That is about regular traffic, not onion traffic. This issue should be closed.
> […](#)
> On Feb 23, 2021, at 23:42, Bzvwf16WSDKoSZd8 ***@***.***> wrote: ﻿ This is not true - onion addresses do not pass through exit nodes and there is no intermediary who has access to the unencrypted stream. All tor traffic have pass through exit nodes finally, exit nodes may see all unencrypted stream. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Reference:
https://support.torproject.org/https/https-1/

Don't just say, give me references of your point -->"traffic data of onion addresses do not pass through exit nodes"

**Comment by gmaxwell** [comment]
https://security.stackexchange.com/questions/51458/is-the-connection-to-tor-hidden-services-encrypted

**Comment by Bzvwf16WSDKoSZd8** [comment]
> https://security.stackexchange.com/questions/51458/is-the-connection-to-tor-hidden-services-encrypted

OK thank you for your answer!
