### ISSUE TITLE
Further discourage use of security mail for support requests

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/bitcoincore.org#760]
There seems to be an influx lately of people mailing the `security@` address for non-security related reasons like getting support. The *(not for support)* is, apparently, not clear enough.

I'm not sure how to address this, but it is annoying regardless. Both for us and for the people thinking they will get support this way and end up ignored.

Maybe redirecting support questions to the bitcoin stack exchange will work better. I don't know.

**Comment by amanciojsilvjr** [comment]
Ok let's study this very patiently

**Comment by harding** [comment]
I think this has been resolved by the merge of #789 .  @laanwj if you disagree, please reopen.  (Anyone else, if you also feel it was adequately addressed, let me know and I'll reopen.)   Thanks!
