### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by Xekyo** [bitcoin-core/bitcoincore.org#77]
Hi!

Good effort on the website, I'm glad this is happening. 

An RSS feed for the blog/articles would be a nice addition.

**Comment by btcdrak** [comment]
There are... :)

**Comment by Xekyo** [comment]
It seems that I was missing something and not you. I just didn't see them anywhere, but apparently they could be found by my feed reader.

**Comment by btcdrak** [comment]
I'm not convinced this should be closed yet. Would it help to put RSS icons anywhere?

**Comment by dexX7** [comment]
> Would it help to put RSS icons anywhere?

Yes.

**Comment by Xekyo** [comment]
Yeah, would be helpful. I was used to getting the link and copying it to my feed reader, I wasn't aware that there was a standard by which it would find the feeds automatically. I didn't think to just put the domain until you wrote that they are in fact available.

**Comment by btcdrak** [comment]
OK, I'll work on something soon.

**Comment by btcdrak** [comment]
Fixed in #152
