### ISSUE TITLE
Bitcoin Core 0.21.1 not visible in Recent Posts

### ISSUE THREAD

**Issue by jsarenik** [bitcoin-core/bitcoincore.org#771]
English (default web) at https://bitcoincore.org/ is not showing the recent post about `0.21.1` release. 

 * https://bitcoincore.org/ja/ shows it
 * https://bitcoincore.org/zh_CN/ shows it
 * https://bitcoincore.org/zh_TW/ as well

**Comment by jsarenik** [comment]
Everything OK now. Thanks!

**Comment by harding** [comment]
@jsarenik glad you got it resolved.  You're actually the second person I've heard of with this issue; it appears to be an issue with browsers serving cached content from the site.  I'm not an expert, but it looks to me like the server is returning the correct HTTP headers to tell browsers that the content has recently been updated, so I'm not sure what's up.

```text
Server: nginx/1.10.3
Date: Sun, 02 May 2021 18:54:41 GMT
Content-Type: text/html
Content-Length: 170611
Last-Modified: Sat, 01 May 2021 21:35:40 GMT
Connection: keep-alive
ETag: "608dc9ac-29a73"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Accept-Ranges: bytes
```

**Comment by jsarenik** [comment]
@harding Thanks for headers. Interesting. They seem all right.

And I just checked that each of the `107.191.99.5` and `198.251.83.116` returns both the same headers and same content. And that the `ETag` header is properly changed (and symetrically returned by both) on a different URL. Interesting.

Maybe just my cache.
