### ISSUE TITLE
No signed data for SHA256SUMS for v22.0

### ISSUE THREAD

**Issue by nolim1t** [bitcoin-core/bitcoincore.org#798]
```
 % curl "https://bitcoincore.org/bin/bitcoin-core-22.0/SHA256SUMS.asc" 2>/dev/null | gpg --verify
gpg: no signed data
gpg: can't hash datafile: No data
```

Also within the file couldn't find any signed hashes as well

**Comment by spinza** [comment]
See #793.  They've split the files into two. Not sure what the correct way to verify is now.

**Comment by nolim1t** [comment]
> See #793.  They've split the files into two. Not sure what the correct way to verify is now.

For verification, Check out https://github.com/lncm/docker-bitcoind/pull/59#issuecomment-918908987

**Comment by MarcoFalke** [comment]
Anything left to do here, after the download page has been reworked: https://bitcoincore.org/en/download/ ?

**Comment by harding** [comment]
> Anything left to do here, after the download page has been reworked: https://bitcoincore.org/en/download/ ?

I don't think so.  Closing now, but happy to reopen upon request.
