### ISSUE TITLE
Segregated Witness Benefits: few perplexities

### ISSUE THREAD

**Issue by gabridome** [bitcoin-core/bitcoincore.org#80]
My english is far from perfect but trying to translate I have seen some sentences with imperfections.

String n.18 on transifex:	- **Wallet authors tracking spent bitcoins:** *it's easiest* to monitor the status of your own outgoing transactions by simply looking them up by txid. But in...

I would have used "it's easier" or "it's the easiest way".

String n.36 on transifex: "In essence, doubling the size of a transaction increases can double both the number of signature operations, and the amount of data that has to be hashed for each of those signatures to be verified. This has been seen in the wild, where an individual block required 25 seconds to validate, and maliciously designed transactions could take over 3 minutes."

"doubling the size of a transaction increases" should be "doubling the size of a transaction"

**Comment by btcdrak** [comment]
ping @ajtowns

**Comment by ajtowns** [comment]
"easiest" seems fine to me; "easier" is for if there's just two things being compared. i can think of three ways of tracking whether a transaction makes it through (by txid, by whether the inputs get spent, by doing bloom filters on the outputs), so "easiest" seems right to me.

I agree "increases" shouldn't be there though

**Comment by gabridome** [comment]
Thank you for spending your time on my consideration. It's a strange
construct to me but English is not my language. Thinking of three things to
be compared, it's provably right what you wrote.
Il 02 feb 2016 4:22 AM, "Anthony Towns" <notifications@github.com> ha
scritto:
