### ISSUE TITLE
BitCoin Core for Mac OS hitting against AVG Antivirus

### ISSUE THREAD

**Issue by GranierLaurent** [bitcoin-core/bitcoincore.org#802]
<img width="614" alt="Capture d’écran 2021-09-17 à 16 25 03" src="https://user-images.githubusercontent.com/62329864/133752723-4232aac9-6694-40f2-826f-175c461ca76d.png">
<img width="371" alt="Capture d’écran 2021-09-17 à 16 40 20" src="https://user-images.githubusercontent.com/62329864/133752735-760b6bf3-4519-454a-bbd9-f7b9022d964d.png">
This issue tracker is for issues with the Bitcoin Core project website at
[bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

**Comment by harding** [comment]
Unfortunately, this tends to happen.  You'll need to contact your antivirus manufacturer and ask them to stop blocking Bitcoin Core.  There are some resources here: https://bitcointalk.org/index.php?topic=5215945.msg53555289#msg53555289

As mentioned in that thread, you maybe be able to rename the file to circumvent the antivirus in the short term.
