### ISSUE TITLE
No RPC docs for version 22.0 on the website

### ISSUE THREAD

**Issue by Ligonsker** [bitcoin-core/bitcoincore.org#820]
As the title says, there is no link to the RPC API of version 22.0 on bitcoincore.org

**Comment by katesalazar** [comment]
$ find _site/en/doc/*/rpc -type d | grep rpc$
    _site/en/doc/0.16.0/rpc
    _site/en/doc/0.16.1/rpc
    _site/en/doc/0.16.2/rpc
    _site/en/doc/0.16.3/rpc
    _site/en/doc/0.17.0/rpc
    _site/en/doc/0.18.0/rpc
    _site/en/doc/0.19.0/rpc
    _site/en/doc/0.20.0/rpc
    _site/en/doc/0.21.0/rpc
    $ _

There is no `_site/en/doc/22.0/rpc`

**Comment by Sjors** [comment]
I believe there's a script that allows anyone to make a PR for a new version, @harding used it last: https://github.com/bitcoin-core/bitcoincore.org/pull/745

**Comment by katesalazar** [comment]
I'm not going to pick this, but I appreciate the hints, thanks.
