### ISSUE TITLE
Ruby 2.5 is EOL

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/bitcoincore.org#825]
We should should jump to 2.7 which is supported by [Debian Stable](https://packages.debian.org/bullseye/ruby2.7) aka Bullseye.

https://www.ruby-lang.org/en/downloads/branches/

https://github.com/bitcoin-core/bitcoincore.org/blob/e0906892db52c94216fc920451ddb76caa2331c3/Gemfile#L3-L7

**Comment by fanquake** [comment]
Looks like Bundler has now given up on us. https://github.com/bitcoin-core/bitcoincore.org/runs/10582082233:
> gem install bundler
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
	bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.5.157.

**Comment by katesalazar** [comment]
been using ruby 2.6 in my local clone for many months *shrugs*
