### ISSUE TITLE
GDPR of iframe youtube?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoincore.org#850]
Might be worth to consider if something needs to be done with youtube iframes. Seee https://github.com/bitcoin-core/bitcoincore.org/pull/848#issuecomment-1014525064 and `git grep '<iframe'`.

**Comment by katesalazar** [comment]
I sorta agree your point that GDPR expands to every jurisdiction
inevitably. Not an expert in the subject,
but that's what everybody told back in the day.  
If everybody universally de facto agrees on that, has agreed on that,
as seen in their actions and cookie policies everywhere, I think it's
others who should prove their point against. I'm willing to read any
legaleze they could want to throw here.  
If agreed, then
as simple as replacing embed iframes for hyperlink anchors.

About removing past historic posts, I think that speaks poorly
and contradictorily about a team who takes proud in
not forking hard the chain and taking care
of a network where rewriting old blocks' history is extremely
difficult.  
But nobody is gonna know.

**Comment by MarcoFalke** [comment]
For reference embedding a font from a google server might already be a violation: https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

**Comment by laanwj** [comment]
Concept ACK on just nuking all references to Google.

**Comment by laanwj** [comment]
> For reference embedding a font from a google server might already be a violation

I don't think we have a need for embedding any special fonts?
