### ISSUE TITLE
Replace references to "the blockchain" to "the distributed blockchain"

### ISSUE THREAD

**Issue by bytting** [bitcoin-core/bitcoincore.org#877]
Replace references to "the blockchain" to "the distributed blockchain" to avoid unnecessary confusion

**Comment by katesalazar** [comment]
no proof that it causes confusion: NAK

**Comment by Zero-1729** [comment]
NACK

Agree with @katesalazar here. Plus, this is somewhat tautological/unnecessary, as it is assumed to be distributed already.

**Comment by MarcoFalke** [comment]
Can someone close this, please?
