### ISSUE TITLE
re: Expired Certificate on Bitcoin Core Download Page - Bitcoin.org

### ISSUE THREAD

**Issue by undersun1** [bitcoin-core/bitcoincore.org#889]
Hello,

I was trying to "Verify release signatures" on the Bitcoin Core download page at https://bitcoin.org/en/download and the certificate for Wladimir J. van der Laan expired on 02/10/2022.  Just wanted to let you know so you can get it updated.  Thanks

![expired certificate](https://user-images.githubusercontent.com/8842451/183270955-dc20064e-a768-49f0-8bf1-d8ad09943d65.jpg)

**Comment by MarcoFalke** [comment]
You can download the latest version on https://bitcoincore.org/en/download/ , not `bitcoin.org`

**Comment by undersun1** [comment]
I downloaded the latest version on https://bitcoincore.org/en/download/ , however all the keys from every signer has expired.  See attached file
[All Keys Expired.txt](https://github.com/bitcoin-core/bitcoincore.org/files/9276712/All.Keys.Expired.txt)

**Comment by undersun1** [comment]
![image](https://user-images.githubusercontent.com/8842451/183531644-31b6b979-a623-4571-abc7-501a6d447e54.png)

**Comment by MarcoFalke** [comment]
Looks like a local issue with your `gpg`. Is this still an issue?

**Comment by fanquake** [comment]
Closing for now.
