### ISSUE TITLE
Improve clarity on the number of release signing keys

### ISSUE THREAD

**Issue by AndySchroder** [bitcoin-core/bitcoincore.org#891]
On the page `2017-01-01-download.md` (https://bitcoincore.org/en/download/) the following phrase suggests that there is a single release signing key,

`verify_checksums_file: "Verify that the checksums file is PGP signed by the release signing key:"`

but the surrounding lines indicate that there are multiple signing keys. I suggest it be changed to

`verify_checksums_file: "Verify that the checksums file is PGP signed by trusted keys:"`

to avoid confusion.

**Comment by superstreber3** [comment]
I think this references this sentence in part 8

> The output of the command above should say that one key was imported, updated, has new signatures, or remained unchanged.

It is always said that it is recommended to use several keys, but in the example one is imported. That's why I think we're talking about **a key**

**Comment by AndySchroder** [comment]
What you say makes sense, but the sentence I've pointed out seems to make it a little contradictory. What about instead changing to 

`verify_checksums_file: "Verify that the checksums file is PGP signed by a trusted release signing key:"`

OR

`verify_checksums_file: "Verify that the checksums file is PGP signed by at least one trusted release signing key:"`

?

**Comment by superstreber3** [comment]
I agree, I created an PR (#894) with the change.

**Comment by MarcoFalke** [comment]
Can be closed?

**Comment by fanquake** [comment]
Ultimately done in #945.
