### ISSUE TITLE
I seem to have found a software bug in the bitcoin core implementation in sha256.cpp

### ISSUE THREAD

**Issue by DivEtImpera** [bitcoin-core/bitcoincore.org#896]
I seem to have found a software bug in the bitcoin core implementation. >> https://github.com/bitcoin/bitcoin/blob/master/src/crypto/sha256.cpp

While function Transform() does this correctly - in the 3 chunk with 64 rounds for each chunk - because block header is 80 bytes long and at the end always the calculated values of the sigma functions flow in (see parameter k of function Round), it's different with function TransformD64 in the 2nd round and there fixed constants are used for parameter k. ;)

With kind regards...

**Comment by fanquake** [comment]
This is the repository for the website. You're probably looking for bitcoin/bitcoin.
