### ISSUE TITLE
arm64 darwin missing from download page

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/bitcoincore.org#917]
arm64 darwin [binaries are available as part of the 23.0 release](https://bitcoincore.org/bin/bitcoin-core-23.0/), however they are not listed on https://bitcoincore.org/en/download/ at all.

**Comment by katesalazar** [comment]
Did anyone mention any plan for publishing dual architecture dmg?
(I suppose that's a thing...)

**Comment by jarolrod** [comment]
@katesalazar why provide a fat binary? Lean binary for each architecture is preferable in my opinion.
