### ISSUE TITLE
Verification docs outdated

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/bitcoincore.org#945]
The verification documentation is outdated. It says to retrieve keys using `contrib/builder-keys/keys.txt`, however this file has been removed in favor of having the keys directly in the guix.sigs repo now. The verification docs need to be updated to reflect this.

**Comment by fanquake** [comment]
See #807, 894, #878 #891 etc

**Comment by MarcoFalke** [comment]
Looks like https://github.com/bitcoin-core/bitcoincore.org/pull/878#issuecomment-1377185769 is up for grabs

**Comment by samybob1** [comment]
In the meantime, [PGP fingerprints are available here](https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md)

**Comment by pinheadmz** [comment]
> See #807, #894, #878 #891 etc

All incorporated into incorporated https://github.com/bitcoin-core/bitcoincore.org/pull/964 now
