### ISSUE TITLE
Is there Bitcoin Core 32 bits for Windows?

### ISSUE THREAD

**Issue by Jeronymos1972** [bitcoin-core/bitcoincore.org#949]
Is there a bitcoin core 32-bits version for Windows?

**Comment by MarcoFalke** [comment]
No, there are only 64-bit versions. IIRC there is no supported version of Windows that is 32-bit at this point? If there is, you'd have to compile it yourself for your version of Windows.

**Comment by Jeronymos1972** [comment]
Good ideia... compile.
Thank you.
