### ISSUE TITLE
Link to Builder keys is broken

### ISSUE THREAD

**Issue by Liongrass** [bitcoin-core/bitcoincore.org#971]
On the [Download page](https://bitcoincore.org/en/download/) there is a section "Verify your Download."
To verify the SHA256SUMS.asc I need a GPG public key, but I cannot obtain this key through the instructions given on the site, as link [builder-keys/keys.txt](https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys/keys.txt) yields a 404.

**Comment by achow101** [comment]
This was fixed in #964. We've been having some issues getting the build server to sync with the web server, hopefully that will be fixed and the changes live later this week.

**Comment by Liongrass** [comment]
Thank you!
