### ISSUE TITLE
Typing error in the French version of the whitepaper

### ISSUE THREAD

**Issue by thisiskeanyvy** [bitcoin-core/bitcoincore.org#978]
- The error is at the end of the file on page 11. The correct term would be "par-à-pair".

![FRENCH_WHITEPAPER](https://github.com/bitcoin-core/bitcoincore.org/assets/48371699/a5b75937-ea7f-47e2-8aa9-d52beb831829)

[https://bitcoin.org/files/bitcoin-paper/bitcoin_fr.pdf](https://bitcoin.org/files/bitcoin-paper/bitcoin_fr.pdf)

**Comment by katesalazar** [comment]
wrong repo

NAK
