### ISSUE TITLE
Revoked key for verification

### ISSUE THREAD

**Issue by RayCryptoLeaner** [bitcoin-core/bitcoincore.org#995]
This issue tracker is for issues with the Bitcoin Core project website at
[bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/issues).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

Hello team, 
I downloaded Bitcoin Core and followed the "bitcoin.org"'s instruction to verify the signature an the archive. 

the instruction is "The 0.11 and later releases are signed by Wladimir J. van der Laan’s releases keywith the fingerprint: 01EA 5486 DE18 A882 D4C2  6845 90C8 019E 36C2 E964"

But when I ran it in my terminal, the result if : "raylinmbp2013@Rays-MacBook-Pro-2023 Downloads % gpg --fingerprint
[keyboxd]
---------
pub   rsa4096 2015-06-24 [SC] [revoked: 2023-02-11]
      01EA 5486 DE18 A882 D4C2  6845 90C8 019E 36C2 E964
uid           [ revoked] Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>
"

The result shows that the key is revoked. 

Could you help update the key?

**Comment by fanquake** [comment]
> [bitcoin.org](https://bitcoin.org/) is not connected with or maintained by the
Bitcoin Core project contributors. Issues with that website should be reported
at [the bitcoin.org](https://github.com/bitcoin-dot-org/bitcoin.org/issues)
